
base_url = "https://ceronman-blog.statichost.eu"

title = "Manuel Cerón's Blog"
description = "A blog mostly about programming languages, programming in general and free/open source software."
author = "Manuel Cerón"
default_language = "en"


build_search_index = false
compile_sass = false
generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
# Put all your custom variables here
